name: deforest
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - dask
  - gdal
  - rasterio
  - rioxarray
  - geopandas
  - shapely
  - pyproj
  - fiona
  - rio-cogeo
  - folium
  - streamlit
  - leafmap
  - localtileserver
  - large-image
  - large-image-source-gdal
  - fastapi
  - uvicorn
  - pip
  - pip:
      - opencv-python-headless
      - pystac-client
      - planetary-computer
      - stackstac