name: deforest
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - dask
  - rasterio
  - rioxarray
  - geopandas
  - shapely
  - pyproj
  - fiona
  - folium
  - streamlit
  - leafmap
  - tqdm
  - pip
  - pip:
      - pystac-client
      - planetary-computer
      - stackstac