site_name: deforestation-viewer
site_url: https://cryoaether.github.io/deforestation-viewer/
repo_url: https://github.com/CryoAether/deforestation-viewer
repo_name: CryoAether/deforestation-viewer

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Install: install.md
  - Create AOI: create_aoi.md
  - NDVI Computation: ndvi.md
  - NDVI Pipeline (search_download): search_download.md
  - Streamlit App: streamlit_app.md
  - Troubleshooting: troubleshooting.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra_css: []
extra_javascript: []