site_name: Deforestation Viewer
site_description: Satellite-based NDVI change detection (1985–2024)
site_author: Lachlan Black
site_url: https://cryoaether.github.io/deforestation-viewer/
repo_url: https://github.com/CryoAether/deforestation-viewer
repo_name: CryoAether/deforestation-viewer

theme:
  name: material
  logo: assets/readme/1995.png   # optional — replace or remove
  favicon: assets/readme/1995.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: light green

nav:
  - Home: index.md
  - Installation: install.md
  - Create AOI: create_aoi.md
  - NDVI Computation: ndvi.md
  - Data Search & Download: search_download.md
  - Streamlit Viewer: streamlit_app.md
  - Troubleshooting: troubleshooting.md