site_name: Deforestation Viewer
site_description: Satellite-based NDVI change detection (1985–2024)
site_author: Lachlan Black
site_url: https://cryoaether.github.io/deforestation-viewer/
repo_url: https://github.com/CryoAether/deforestation-viewer
repo_name: CryoAether/deforestation-viewer
edit_uri: blob/main/docs/

docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.integrate
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: green
      accent: light green
  logo: ../assets/readme/1995.png     # root-based assets
  favicon: ../assets/readme/1995.png

nav:
  - Home: index.md
  - Install: install.md
  - Create AOI: create_aoi.md
  - NDVI Computation: ndvi.md
  - NDVI Pipeline (search_download): search_download.md
  - Streamlit App: streamlit_app.md   # <-- rename from streamlit.md
  - Troubleshooting: troubleshooting.md
  
plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CryoAether
      name: GitHub